[package]
name = "ZingUSDC"
edition = "2024.beta" # edition = "legacy" to use legacy (pre-2024) Move
# license = ""           # e.g., "MIT", "GPL", "Apache 2.0"
# authors = ["..."]      # e.g., ["Joe Smith (joesmith@noemail.com)", "John Snow (johnsnow@noemail.com)"]

[dependencies]
ZingFramework = { local = "../zing_framework/" }
ZingVault = { local = "../zing_vault/" }
ZingBank = { local = "../zing_bank/" }
ScallopProtocol = { git = "https://github.com/scallop-io/sui-lending-protocol.git",  subdir = "contracts/protocol", rev = "main" }
lending_core = { git = "https://github.com/Jarekkkkk/navi-interface.git", subdir = "lending_core", rev = "main" }
oracle = { git = "https://github.com/Jarekkkkk/navi-interface.git", subdir = "oracle", rev = "main" }

[addresses]
zusdc = "0x00"
math_navi = "0xad013d5fde39e15eabda32b3dbdafd67dac32b798ce63237c27a8f73339b9b6f"
# Named addresses will be accessible in Move as `@name`. They're also exported:
# for example, `std = "0x1"` is exported by the Standard Library.
# alice = "0xA11CE"

[dev-dependencies]
# The dev-dependencies section allows overriding dependencies for `--test` and
# `--dev` modes. You can introduce test-only dependencies here.
# Local = { local = "../path/to/dev-build" }

[dev-addresses]
# The dev-addresses section allows overwriting named addresses for the `--test`
# and `--dev` modes.
# alice = "0xB0B"

